spring:
  sql:
    init:
      mode: always
      platform: h2
  datasource:
#    url: jdbc:h2:file:/data/demo // Use this url to save the database to a file.
    url: jdbc:h2:mem:h2db
    username: sa
    password: password
    driverClassName: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect
    initialization-mode: always
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
jwt:
  secret: "81a0b662bed90dbd805f73c20408c36d351af60ab84f7bb9066994031e8b3811"